### PR TITLE
use PERL_NO_GET_CONTEXT for more performance

### PR DESCRIPTION
**Pull request by markusbeth**

### CODE REVIEW

**Comment by mjegh** [comment]
Having a problem with this change. It worked for me but a friend who has a threaded perl got:

```
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/perl.h:176:16: error: ‘my_perl’ undeclared (first use in this function); did you my_fork’?

perl -v

This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi
(with 67 registered patches, see perl -V for more detail)

uname -a
Linux desktop 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux 
```

**Comment by mjegh** [comment]
I think some pTHX_ and aTHX_ are missing.

**Comment by mjegh** [comment]
http://blogs.perl.org/users/nick_wellnhofer/2015/03/writing-xs-like-a-pro---perl-no-get-context-and-static-functions.html

**Comment by mjegh** [comment]
I think unicode_helper.c is missing the context changes:

```
x86_64-linux-gnu-gcc -c -DWITH_UNICODE -DHAVE_UNISTD_H -DHAVE_PWD_H -DHAVE_SYS_TYPES_H -DHAVE_LONG_LONG -DSIZEOF_LONG_INT=8 -I/usr/local/include  -I/usr/local/include -I. -I/usr/lib/x86_64-linux-gnu/perl5/5.26/auto/DBI -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g   -DVERSION=\"1.61\" -DXS_VERSION=\"1.61\" -fPIC "-I/usr/lib/x86_64-linux-gnu/perl/5.26/CORE"  -DWITH_UNICODE -DHAVE_UNISTD_H -DHAVE_PWD_H -DHAVE_SYS_TYPES_H -DHAVE_LONG_LONG -DSIZEOF_LONG_INT=8 -I/usr/local/include  -I/usr/local/include unicode_helper.c
In file included from /usr/lib/x86_64-linux-gnu/perl5/5.26/auto/DBI/DBIXS.h:23:0,
                 from ODBC.h:14,
                 from unicode_helper.c:3:
unicode_helper.c: In function ‘_dosvwv’:
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/perl.h:176:16: error: ‘my_perl’ undeclared (first use in this function); did you mean ‘my_fork’?
 #  define aTHX my_perl
                ^
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/perl.h:189:18: note: in expansion of macro ‘aTHX’
 #  define aTHX_  aTHX,
                  ^~~~
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/embed.h:420:38: note: in expansion of macro ‘aTHX_’
 #define newSVpvn(a,b)  Perl_newSVpvn(aTHX_ a,b)
                                      ^~~~~
unicode_helper.c:96:12: note: in expansion of macro ‘newSVpvn’
         sv=newSVpvn(p,svlen);
            ^~~~~~~~
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/perl.h:176:16: note: each undeclared identifier is reported only once for each function it appears in
 #  define aTHX my_perl
                ^
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/perl.h:189:18: note: in expansion of macro ‘aTHX’
 #  define aTHX_  aTHX,
                  ^~~~
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/embed.h:420:38: note: in expansion of macro ‘aTHX_’
 #define newSVpvn(a,b)  Perl_newSVpvn(aTHX_ a,b)
                                      ^~~~~
unicode_helper.c:96:12: note: in expansion of macro ‘newSVpvn’
         sv=newSVpvn(p,svlen);
            ^~~~~~~~
unicode_helper.c: In function ‘sv_setwvn’:
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/perl.h:176:16: error: ‘my_perl’ undeclared (first use in this function); did you mean ‘my_fork’?
 #  define aTHX my_perl
                ^
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/perl.h:189:18: note: in expansion of macro ‘aTHX’
 #  define aTHX_  aTHX,
                  ^~~~
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/embed.h:691:41: note: in expansion of macro ‘aTHX_’
 #define sv_setpvn(a,b,c) Perl_sv_setpvn(aTHX_ a,b,c)
                                         ^~~~~
unicode_helper.c:137:9: note: in expansion of macro ‘sv_setpvn’
         sv_setpvn(sv,NULL,len);
         ^~~~~~~~~
unicode_helper.c: In function ‘sv_newwvn’:
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/perl.h:176:16: error: ‘my_perl’ undeclared (first use in this function); did you mean ‘my_fork’?
 #  define aTHX my_perl
                ^
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/embedvar.h:38:18: note: in expansion of macro ‘aTHX’
 #    define vTHX aTHX
                  ^~~~
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/embedvar.h:324:23: note: in expansion of macro ‘vTHX’
 #define PL_sv_undef  (vTHX->Isv_undef)
                       ^~~~
unicode_helper.c:152:15: note: in expansion of macro ‘PL_sv_undef’
         sv = &PL_sv_undef;
               ^~~~~~~~~~~
unicode_helper.c: In function ‘SV_toWCHAR’:
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/perl.h:176:16: error: ‘my_perl’ undeclared (first use in this function); did you mean ‘my_fork’?
 #  define aTHX my_perl
                ^
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/perl.h:189:18: note: in expansion of macro ‘aTHX’
 #  define aTHX_  aTHX,
                  ^~~~
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/embed.h:665:53: note: in expansion of macro ‘aTHX_’
 #define sv_pvutf8n_force(a,b) Perl_sv_pvutf8n_force(aTHX_ a,b)
                                                     ^~~~~
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/sv.h:1729:40: note: in expansion of macro ‘sv_pvutf8n_force’
      ? ((lp = SvCUR(sv)), SvPVX(sv)) : sv_pvutf8n_force(sv, &lp))
                                        ^~~~~~~~~~~~~~~~
unicode_helper.c:356:7: note: in expansion of macro ‘SvPVutf8_force’
     p=SvPVutf8_force(sv,len);
       ^~~~~~~~~~~~~~
unicode_helper.c: In function ‘utf8sv_to_wcharsv’:
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/perl.h:176:16: error: ‘my_perl’ undeclared (first use in this function); did you mean ‘my_fork’?
 #  define aTHX my_perl
                ^
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/perl.h:189:18: note: in expansion of macro ‘aTHX’
 #  define aTHX_  aTHX,
                  ^~~~
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/embed.h:711:47: note: in expansion of macro ‘aTHX_’
 #define sv_utf8_decode(a) Perl_sv_utf8_decode(aTHX_ a)
                                               ^~~~~
unicode_helper.c:372:5: note: in expansion of macro ‘sv_utf8_decode’
     sv_utf8_decode(sv);
     ^~~~~~~~~~~~~~
Makefile:392: recipe for target 'unicode_helper.o' failed
make: *** [unicode_helper.o] Error 1
```

**Comment by mjegh** [comment]
@markusbeth would you consider fixing this and resubmitting? Otherwise I'll revert soon so I can do a release. BTW, thanks for the effort.

**Comment by markusbeth** [comment]
@mjegh sorry for this oversight. See PR #17 for a fix.

**Comment by mjegh** [comment]
thanks. I've merged and will release 1.61 later today.

**Pull request merged**
