### PR TITLE
update the perl versions currently supported by travis

### PR DESCRIPTION
**Pull request by markusbeth**

### CODE REVIEW

**Comment by pali** [comment]
Alternative `.travis.yml` file which does not remove support for testing older Perl versions which are still supported by DBD::ODBC:
```yaml
before_install:
 - sudo apt-get update
 - sudo apt-get install -qq unixodbc unixodbc-dev
 - sudo apt-get install -qq libsqliteodbc
 - if [ -z "$PERLBREW_PERL" ]; then eval $(curl https://travis-perl.github.io/init) --auto; fi
env:
 global:
   - DBI_DSN=dbi:ODBC:DRIVER=SQLite3
 matrix:
   - DBD_ODBC_UNICODE=1
   - 
language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.22-shrplib"
  - "5.24"
  - "5.24-shrplib"
  - "5.26"
  - "5.26-shrplib"
  - "5.28"
  - "5.30"
notifications:
  email:
    recipents:
      - mjevans@cpan.org
    on_success: always
    on_failure: always
  irc:
    channels:
      - "irc.perl.org#dbi"
    on_success: change
    on_failure: always
```
If official travis does not support particular Perl version then script fallbacks to use Perl from unofficial (but better) travis-perl project.

I suggest to do not drop testing of old Perl versions which are still usable with DBD::ODBC.

**Comment by pali** [comment]
@markusbeth Any reason why not to test old perl versions?

**Comment by markusbeth** [comment]
There is absolutely no reason to not test old perl versions as long as the tests work as expected. When I opened PR #13 travis told me that almost all tests failed. But the tests do not fail due to my changes but because the configured perl version could not be installed. As I did not know about the travis-perl project the only (or simplest) solution in my eyes was to adapt the perl versions to test to those officially provided by travis.
If the alternative .travis.yml file from @pali also makes the tests to succeed (even for the old perl versions) I would be happy to see this in the repository.

**Comment by pali** [comment]
I created PR https://github.com/perl5-dbi/DBD-ODBC/pull/16 with my above approach.

**Comment by mjegh** [comment]
Does your approach @pali work as I've not seen a successful run through. I'm happy to merge it if it works.

**Comment by pali** [comment]
@mjegh currently it is failing on error:
```
Press return to continue...  

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```
And message `Press return to continue...` comes from Makefile.PL, line 212:
https://github.com/perl5-dbi/DBD-ODBC/blob/336fe9772aefa849e6492ff861e809dcae37829f/Makefile.PL#L201-L213
Is there a way how to avoid waiting for `return` key which on Travis obviously cannot be pressed?

**Comment by mjegh** [comment]
Is there something set in Travis the script can check for so we don't prompt on Travis.

**Comment by pali** [comment]
Now I'm looking at that `PERL_MM_USE_DEFAULT` comment. Seems that this could be a key to avoiding asking for prompt.

**Comment by mjegh** [comment]
In general you can detect if you are on Travis-CI by checking the environment variables. You can check either for CI=true or the more specific TRAVIS=true

**Comment by pali** [comment]
Setting `PERL_MM_USE_DEFAULT=1` helped. Now there is no waiting for pressing key. And tests passed in that PR #16 passed.

**Pull request closed without merging**
